language: csharp
mono: none
dotnet: 2.1.302
node_js:
  - "9.11.1"
branches:
  only:
    - master
before_script:
  - sudo chmod +x scripts/build.sh
  - npm install -g @angular/cli@6.0.1
  - (cd web/ && npm install)
script:
  - (cd scripts/ && ./build.sh)
  - dotnet test ./BoltJwtUnitTest/