language: csharp
mono: none
dotnet: 2.1.300-preview1-008174
node_js:
  - "8.2.1"
branches:
  only:
    - master
before_script:
  - sudo chmod +x scripts/build.sh
  - npm install -g @angular/cli@1.6.3
  - (cd web/ && npm install)
script:
  - (cd scripts/ && ./build.sh)
  - dotnet test ./BoltJwtUnitTest/