language: csharp
mono: none
dotnet: 2.0.3
node_js:
  - "8.2.1"
branches:
  only:
    - master
before_script:
  - sudo chmod +x build/build.sh
  - npm install -g @angular/cli@1.6.3
  - (cd web/ && npm install)
script:
  - (cd build/ && ./build.sh)
  - dotnet test ./BoltJwtUnitTest/